[package]
name = "sach"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etc = { version = "0.1.2", features = "bonus" }
toml = "0.5.6"
